#ifndef _BAREBOX_CONFIG_H
#define _BAREBOX_CONFIG_H

#define CONFIG_HAS_DEBUG_LL
#define CONFIG_DEBUG_LL
#define CONFIG_BAUDRATE		115200

#define CONFIG_CLOCKSOURCE_DUMMY_RATE 0x40000

#endif /* _BAREBOX_CONFIG_H */
